# Spawn locations for yellow boxes in the proper_field world
# Format: List of {x, y, z} dictionaries
robot:
  x: 0.25
  y: -1.0
  z: 0.2
  yaw: 0.0

locations:
  - { x: 1.830000, y: -.27, z: 0.05 }
  - { x: 1.302910, y: -0.194908, z: 0.05 }
  - { x: 1.0, y: -0.742004, z: 0.05 }
  - { x: 0.784732, y: -1.047450, z: 0.05 }
  - { x: 0.624254, y: -0.549913, z: 0.05 }
  - { x: 1.899290, y: -1.0, z: 0.05 }
