ekf_node:
  ros__parameters:
    frequency: 30.0

    two_d_mode: true
    publish_tf: true

    map_frame: map              # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_link  # Defaults to "base_link" if unspecified
    world_frame: odom           # Defaults to the value of odom_frame if unspecified

    odom0: /odom/unfiltered

    odom0_config: [false, false, false,
                      false, false, false,
                      true,  false, false,
                      false, false, true,
                      false, false, false]

    odom0_differential: false
    odom0_relative: false

    imu0: /mcu_robot/imu/data

    imu0_config: [false, false, false,
                      false, false, true,
                      false,  false, false,
                      false, false, true,
                      false, false, false]

    # use absolute yaw
    imu0_differential: false
    # not sure here
    imu0_relative: false